name: Test Installer

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    container: ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run installer
        run: ./bootstrap.sh
